# FROM node:20-alpine

# # コンテナ内での作業ディレクトリを指定
# WORKDIR /app

# # まず、依存関係のファイルのみをコピーする
# # これにより、依存関係に変更がない限りキャッシュが利用され、ビルドが高速化します
# COPY package*.json ./

# # 依存関係をインストール
# RUN npm install

# # プロジェクトの全てのファイルをコピー
# COPY . .

# # Next.jsが使用するポート3000番を開放
# EXPOSE 3000

# # コンテナ起動時に開発サーバーを起動するコマンド
# CMD ["npm", "run", "dev"]

# === 1) ベースイメージ =========
FROM node:20-alpine AS base
# ビルド時に変数を受け取るための記述を追加
ARG NEXT_PUBLIC_API_BASE
ARG NEXT_PUBLIC_API_KEY

# 受け取った変数をコンテナの環境変数として設定
ENV NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE
ENV NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY

WORKDIR /app

WORKDIR /app

# === 2) 依存関係レイヤ ==========
# package.json と lockfile だけコピーしてキャッシュを効かせる
COPY package*.json ./
RUN npm ci

# === 3) アプリケーション =========
# コードをホットリロードしたいので docker‑compose の volume で上書き,
# ここでは COPY しない  (ビルドは不要)
EXPOSE 3000
CMD ["npm", "run", "dev"]
